name: run_script
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib
      - name: Run Code
        run: python main.py
      - name: Check output
        run: |
            if grep -q "Fortran bad" output.txt; then
              echo "NO BLASPHEMY"
            else
              echo "BLASPHEMPY DETECTED"
              exit 1
            fi
                   
